language: fortran
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gfortran-5']
      env: gfortran=gfortran-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gfortran-6']
      env: gfortran=gfortran-6


script:
  gfortran --version