language: python

compiler:
  - gcc

sudo: false #true

matrix:
  include:
    - python: 3.6


cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.local

addons:
  apt:
    sources:
      - kalakris-cmake
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-5
      - binutils
      - cmake
      - graphviz
      - python-pip


# command to install dependencies
install:
    - |
      if [[ ! -d "$HOME/.local/bin" ]]; then
        mkdir "$HOME/.local/bin"
      fi
    - export PATH="$HOME/.local/bin:$PATH"
    - export FC=/usr/bin/gfortran-5
    - ln -fs /usr/bin/gfortran-5 "$HOME/.local/bin/gfortran" && gfortran --version
    - ls -l /usr/bin/gfortran-5
    - pip install -r requirements.travis.txt
    - pip install https://github.com/modflowpy/flopy/zipball/develop
    - pip install https://github.com/modflowpy/pymake/zipball/master

# command to run tests
script: 
    - export PYTHONPATH=$PYTHONPATH:.
    - cd autotest
    - nosetests -v
