language: fortran
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gfortran-5','python-pip']
      env: 
        - PYTHON_VERSION=3.6
        - CVER="gfortran5"
        - COMPILER=gfortran-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gfortran-6','python-pip']
      env: 
        - PYTHON_VERSION=3.6
        - CVER="gfortran6"
        - COMPILER=gfortran-6

install:
    - |
      if [[ ! -d "$HOME/.local/bin" ]]; then
        mkdir "$HOME/.local/bin"
      fi
    - export PATH="$HOME/.local/bin:$PATH"
    - if [[ $CVER == "gfortran5" ]]; then
        ln -fs /usr/bin/gfortran-5 "$HOME/.local/bin/gfortran";
        gfortran --version;
        ls -l /usr/bin/gfortran-5;
      fi
    - if [[ $CVER == "gfortran6" ]]; then
        ln -fs /usr/bin/gfortran-6 "$HOME/.local/bin/gfortran";
        gfortran --version;
        ls -l /usr/bin/gfortran-6;
      fi
    - pip install -r requirements.travis.txt
    - pip install https://github.com/modflowpy/flopy/zipball/develop
    - pip install https://github.com/modflowpy/pymake/zipball/master


script:
    - gfortran --version
    - export PYTHONPATH=$PYTHONPATH:.
    - cd autotest
  