language: fortran
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages: 
            - gfortran-5
            - python3.5-complete
            - python-pip
            - texlive-base
            - texlive-latex-base
            - texlive-latex-extra
            - texlive-latex-recommended
            - texlive-science
            - texlive-fonts-recommended
            - texlive-fonts-extra
            - dpkg
            - tex-common
            - latex-xcolor
      env: 
        - CVER="gfortran5"
        - COMPILER=gfortran-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages: 
            - gfortran-6
            - python3.5-complete
            - python-pip
            - texlive-base
            - texlive-latex-base
            - texlive-latex-extra
            - texlive-latex-recommended
            - texlive-science
            - texlive-fonts-recommended
            - texlive-fonts-extra
            - dpkg
            - tex-common
            - latex-xcolor
      env: 
        - CVER="gfortran6"
        - COMPILER=gfortran-6

#    - os: osx
#      osx_image: xcode8.3
#      compiler: gcc
#      env: 
#        - CVER="gfortran5"
#        - COMPILER=gfortran-5
#        - CXX_COMPILER='g++-5'
#        - C_COMPILER='gcc-5'
#        - Fortran_COMPILER='gfortran'
#        - BUILD_TYPE='Release'


install:
#    - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
#        brew install python gcc;
#      fi
    - if [[ ! -d "$HOME/.local/bin" ]]; then
        mkdir "$HOME/.local/bin";
      fi
    - export PATH="$HOME/.local/bin:$PATH"
    - if [[ $CVER == "gfortran5" ]]; then
        ln -fs /usr/bin/gfortran-5 "$HOME/.local/bin/gfortran";
        gfortran --version;
        ls -l /usr/bin/gfortran-5;
      fi
    - if [[ $CVER == "gfortran6" ]]; then
        ln -fs /usr/bin/gfortran-6 "$HOME/.local/bin/gfortran";
        gfortran --version;
        ls -l /usr/bin/gfortran-6;
      fi
    - echo "$PYTHONPATH"
    - export PYTHONPATH=$PYTHONPATH:.
    - pip install -r requirements.travis.txt
    - pip install https://github.com/modflowpy/flopy/zipball/develop
    - pip install https://github.com/modflowpy/pymake/zipball/master


script:
    - python --version
    - which python
    - cd autotest
    - nosetests -v
