language: fortran
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gfortran-5']
      env: gfortran=gfortran-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gfortran-6']
      env: gfortran=gfortran-6

install:
    - export PATH="$HOME/.local/bin:$PATH"
    - |
      if [[ -d "/usr/bin/gfortran-5" ]]; then
        export FC=/usr/bin/gfortran-5
        ln -fs /usr/bin/gfortran-5 "$HOME/.local/bin/gfortran" && gfortran --version
        ls -l /usr/bin/gfortran-5
      fi
    - |
      if [[ -d "/usr/bin/gfortran-6" ]]; then
        export FC=/usr/bin/gfortran-6
        ln -fs /usr/bin/gfortran-6 "$HOME/.local/bin/gfortran" && gfortran --version
        ls -l /usr/bin/gfortran-6
      fi


script:
  gfortran --version