language: fortran
matrix:
  include:
    - os: linux
      compiler: gcc
      python: 3.5
      cache:
        apt: true
        pip: true
        directories:
          - $HOME/.cache/pip
          - $HOME/.local
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages: 
            - gfortran-5
            - python3-pip
            - python3-nose
#            - texlive-base
#            - texlive-latex-base
#            - texlive-latex-extra
#            - texlive-latex-recommended
#            - texlive-science
#            - texlive-fonts-recommended
#            - texlive-fonts-extra
#            - dpkg
#            - tex-common
#            - latex-xcolor
      env: 
        - CVER="gfortran5"
        - COMPILER=gfortran-5

    - os: linux
      compiler: gcc
      python: 3.5
      cache:
        apt: true
        pip: true
        directories:
          - $HOME/.cache/pip
          - $HOME/.local
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages: 
            - gfortran-6
            - python3-pip
            - python3-nose
#            - texlive-base
#            - texlive-latex-base
#            - texlive-latex-extra
#            - texlive-latex-recommended
#            - texlive-science
#            - texlive-fonts-recommended
#            - texlive-fonts-extra
#            - dpkg
#            - tex-common
#            - latex-xcolor
      env: 
        - CVER="gfortran6"
        - COMPILER=gfortran-6

#    - os: osx
#      osx_image: xcode8.3
#      compiler: gcc
#      env: 
#        - CVER="gfortran5"
#        - COMPILER=gfortran-5
#        - CXX_COMPILER='g++-5'
#        - C_COMPILER='gcc-5'
#        - Fortran_COMPILER='gfortran'
#        - BUILD_TYPE='Release'


install:
#    - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
#        brew install python gcc;
#      fi
    - if [[ ! -d "$HOME/.local/bin" ]]; then
        mkdir "$HOME/.local/bin";
      fi
    - export PATH="$HOME/.local/bin:$PATH"
    - if [[ $CVER == "gfortran5" ]]; then
        ln -fs /usr/bin/gfortran-5 "$HOME/.local/bin/gfortran";
        gfortran --version;
        ls -l /usr/bin/gfortran-5;
      fi
    - if [[ $CVER == "gfortran6" ]]; then
        ln -fs /usr/bin/gfortran-6 "$HOME/.local/bin/gfortran";
        gfortran --version;
        ls -l /usr/bin/gfortran-6;
      fi
#     python nightmare
    - which python3
    - python3 --version
    - which pip3
    - pip3 --version
    - which nosetests3
    - nosetests3 --version
    - ln -fs /opt/python/3.5.3/bin/python3 "$HOME/.local/bin/python"
    - ln -fs /opt/python/3.5.3/bin/nosetests3 "$HOME/.local/bin/nosetests"
    - which python
    - python --version
    - which nosetests
    - nosetests --version
    - pip install -r requirements.travis.txt
    - pip install https://github.com/modflowpy/flopy/zipball/develop
    - pip install https://github.com/modflowpy/pymake/zipball/master


script:
    - which python
    - python --version
    - cd autotest
    - nosetests -v
