language: fortran
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gfortran-5']
      env: 
        - CVER="gfortran5"
        - COMPILER=gfortran-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gfortran-6']
      env: 
        - CVER="gfortran6"
        - COMPILER=gfortran-6

install:
    - |
      if [[ ! -d "$HOME/.local/bin" ]]; then
        mkdir "$HOME/.local/bin"
      fi
    - export PATH="$HOME/.local/bin:$PATH"
    - if [[ $CVER == "gfortran5" ]]; then
        ln -fs /usr/bin/gfortran-5 "$HOME/.local/bin/gfortran";
        gfortran --version;
        ls -l /usr/bin/gfortran-5;
      fi
    - if [[ $CVER == "gfortran6" ]]; then
        ln -fs /usr/bin/gfortran-6 "$HOME/.local/bin/gfortran";
        gfortran --version;
        ls -l /usr/bin/gfortran-6;
      fi
include:
  - python: 3.6
cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.local
addons:
  apt:
    packages:
      - python-pip
      - texlive-base
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-latex-recommended
      - texlive-science
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - dpkg
      - tex-common
      - latex-xcolor


script:
  gfortran --version